### ISSUE TITLE
When input is `required` the `_validateCount` increases while the validate function is not being called

### ISSUE THREAD

**Issue by MiroslavPetrik** [form-atoms/form-atoms#49]
Have regular input with native `required` prop. When this input is empty, browser traps the submit event and displays the native popup window requiring user to fill this input.

Currently the `_validateCount` increases with every submit while the `validate` function is not being called. 

[Here is codesandbox demo](https://codesandbox.io/s/validatecount-increases-without-validate-call-e4rgh8?file=/src/App.tsx) with two inputs. 

Steps:

0. open console
1. submit the form 
2. observe that nothing is logged, the input has popup "please fill out this form"
3. submit the form again
4. in console it logs `{name: "first", validateStatus: "valid", _validateCount: 1}`

For me the increasing `_validateCount` is a problem, as I use it in conjunction with the `aria-invalid` prop.
When a field is required, I set the `aria-invalid` to `_validateCount > 0 && validateStatus === "invalid"`

Since the `"valid"` is initial value of the `_validateStatus` atom, my inputs get the `aria-invalid="false"` prop [which colors inputs in green when you submit twice](https://miroslavpetrik.github.io/form-atoms-field/?path=/docs/fields-checkboxfield--docs#required)

I understand that the atoms prefixed with `_` are internals, and likely should not be used for this `aria-invalid` behavior.

I think the solution here is not to stop the validateCount from increasing, but instead have a new `validatedCount` atom which will indicate that the field _did validate in the past_. Since the `validate` function did not run, it will stay 0, so I won't see the false-positive value of `aria-invalid=false`.

Also this would solve one other issue for me - the `_validateCount` is not being reset when the form state is reset (which is ok, since it's internal thing) so having the `validatedCount` would be a public API.

This started like a bug initially, but since I don't have other solution in mind consider this a feature request.

**Comment by MiroslavPetrik** [comment]
For more background, here is the `aria-invalid` behavior 
https://github.com/MiroslavPetrik/form-atoms-field/commit/334d276bf08b36e6a012caa60164cff68b161712

**Comment by jaredLunde** [comment]
Is there a reason checking for an error count doesn't suffice for the `aria-invalid` case?

**Comment by jaredLunde** [comment]
Validate count is an internal that's used as an ID to prevent race conditions. It doesn't really need to be so accurate as designed.

**Comment by MiroslavPetrik** [comment]
> Is there a reason checking for an error count doesn't suffice for the `aria-invalid` case?

By definition the `validateStatus` already indicates the error count:
- when `0` errors then `"valid"`
- when `> 0` errors then `"invalid"`

So practically I'm already using the error count.

The `validateStatus` is part of the problem, because it has initial value of `"valid"` which causes my inputs to be highlighted green when the validateCount increments.

In reality, since the validation did not run, the `validateStatus` could be `undefined` since we don't know the real field validation status...

What do you think about that?

**Comment by MiroslavPetrik** [comment]
As another approach, I've used the [`submitCount` from the `formAtom`](https://github.com/MiroslavPetrik/form-atoms-field/commit/ecd8beb3e7765e61f59710d800d0d0a3123fa146#diff-fb2d96cb7a1f3bcdd9b191f965bccb2435897c6161a819a1d0803de18d5abc12R43). 

It requires a context to provide the formAtom (since the field atoms do not have the 'submitCount'), so all the field components can access the form state.
It fixes the 'false positive' case when the validateStatus is initially "valid" but the validation did not run.

With this change, the inputs are colored green only when they are properly filled & form is submitted.

But it has another drawback, that we don't have the field set to `aria-invalid="false"` right away when it's filled properly - e.g. when required checkbox is checked.

The `submitCount > 0` helps to distinguish the "initially pseudo-valid" from "valid after real user change" scenarios.
But it's too strict since we could color the input green as soon as the user checks the input, but that requires some other state to rely on:
- start `validateStatus` as `undefined` so it becomes `valid` after validation when user did real change
- count `validateDCount` for each field properly from 0, also respecting the `reset` action
- add `changed` atom indicating whether user acted with `change` event on the field (notice that `dirty` atom cannot be used)

**Comment by jaredLunde** [comment]
Couldn't you just choose to validate on mount and then check `dirty` and `touched` in your validator?

**Comment by MiroslavPetrik** [comment]
The root issue is that the initial validation status ("valid") without user changing the input is indistinguishable from "valid" state after user caused some validation event.

Validate on mount - how would you do that? I've already tried to call `validate` function in an effect hook. IMHO this is bad practice as it points out either that the initial value for the validateStatus is poorly chosen or simply it is missing initializer.
I have animated styles on my inputs, so the quick change from "valid" to "invalid" animates the form when rendered which is bad.

**Comment by jaredLunde** [comment]
I would argue any initially invalid state is bad UX? Like "why are you yelling at me? I didn't even do anything yet"

Do other form libraries validate right away?

**Comment by jaredLunde** [comment]
Works as designed
