### ISSUE TITLE
Debug label not set in vite

### ISSUE THREAD

**Issue by schiller-manuel** [form-atoms/form-atoms#51]
In vite, `process` is not defined (though `process.env.NODE_ENV` is working) and thus the`typeof process !== "undefined"` check fails in

https://github.com/jaredLunde/form-atoms/blob/727c25073a912188251ace8bc2f08dbfae84188a/src/index.tsx#L372C7-L372C37

https://github.com/jaredLunde/form-atoms/blob/727c25073a912188251ace8bc2f08dbfae84188a/src/index.tsx#L714C7-L714C37

So in the Jotai DevTools, all form/field atoms are unlabeled:
![Screenshot 2023-10-15 at 22 36 53](https://github.com/jaredLunde/form-atoms/assets/6340397/ab971de6-f103-4cfd-be2e-fd7abb530394)

**Comment by MiroslavPetrik** [comment]
As a quick fix you can update your vite config:

```ts
import { defineConfig } from 'vite'
// ...
export default defineConfig({
  // ...
  define: {
    'process.env': {}
  }
})
```

But maybe we should update the check to use the `import.meta.env.MODE` instead
https://vitejs.dev/guide/env-and-mode.html

**Comment by jaredLunde** [comment]
I'm not willing to create a special check for every bundler that pops up in node. The `process` check is fairly standard in node libraries including React.
