### ISSUE TITLE
Outdated lockfile?

### ISSUE THREAD

**Issue by MiroslavPetrik** [form-atoms/form-atoms#58]
When I install project with `pnpn` it creates a lockfile with new version:
![image](https://github.com/form-atoms/form-atoms/assets/38855190/235ca990-0a40-4c1d-9421-1ebbb70036d8)

Likely we want to update the project lockfile?

**Comment by jaredLunde** [comment]
yeah this must have been created with pnpm 5. feel free to upgrade it : )

**Comment by MiroslavPetrik** [comment]
the lockfile v6 needs pnpm >= 8.6
