### ISSUE TITLE
Field & Form atoms should be of `PrimitiveAtom` type

### ISSUE THREAD

**Issue by MiroslavPetrik** [form-atoms/form-atoms#71]
**Describe the bug**
Form atom is [defined as `Atom<...>`](https://github.com/form-atoms/form-atoms/blob/0b7fbfd5e71abf69944197bc8b5c1dec28958064/src/index.tsx#L1556).
The same is true for [`FieldAtom`](https://github.com/form-atoms/form-atoms/blob/0b7fbfd5e71abf69944197bc8b5c1dec28958064/src/index.tsx#L1464)

in practice, jotai[ `atom(initialValue)` call returns a `PrimitiveAtom`](https://github.com/pmndrs/jotai/blob/90d3969a51b5a60b7844253ac11715b53212e17b/src/vanilla/atom.ts#L85) which has a write method.

**To Reproduce**
try setting a field or form atom's value:

```ts
const f = fieldAtom()

// type err, f has no write method
set(f, get(f)); 
```

**Expected behavior**
The write via `set` should work.

**Screenshots**
![image](https://github.com/form-atoms/form-atoms/assets/38855190/df47b4db-53bc-4893-ad24-c79ce447d824)

- Version: 3.2.4

**Additional context**
Other atoms could use the `PrimitiveAtom` in type definitions. e.g.
- errors https://github.com/form-atoms/form-atoms/blob/0b7fbfd5e71abf69944197bc8b5c1dec28958064/src/index.tsx#L1504
- validateCount https://github.com/form-atoms/form-atoms/blob/0b7fbfd5e71abf69944197bc8b5c1dec28958064/src/index.tsx#L1548
- ...

**Comment by jaredLunde** [comment]
Field atoms are intentionally not writable

**Comment by MiroslavPetrik** [comment]
Do you see it as a footgun?
Shouldn't the types reflect the reality present in javascript? Now the type only hides the write method, but it is there.

Last, what about simplifying the types of the writable atoms mentioned in additional context?

**Comment by jaredLunde** [comment]
Not changing anything.
