### ISSUE TITLE
Examples: Validation Option Valibot along with zod

### ISSUE THREAD

**Issue by pgangwani** [form-atoms/form-atoms#73]
**Is your feature request related to a problem? Please describe.**
As per [this blog]( https://www.builder.io/blog/valibot-bundle-size) and intention of this library to the smallest, Can we try to use valibot instead of zod.

This is purely to reduce the bundle size and keeping smallest chunk of peer dependencies to this library.

**Describe the solution you'd like**
I am looking if there is need of some work from this library so that its supported out of the box and looking for examples

**Describe alternatives you've considered**

**Additional context**
Similar work was done jotai labs too [Reference](https://github.com/jotaijs/jotai-form/pull/21)

**Comment by pgangwani** [comment]
@MiroslavPetrik  @jaredLunde Please review whenver you get time.

**Comment by jaredLunde** [comment]
Yeah I'm down to add a Valibot example
