### ISSUE TITLE
Why the additional re-render?

### ISSUE THREAD

**Issue by wuleninja** [form-atoms/form-atoms#77]
**Describe the _question_**

I'm quite new to React, so that may be a trivial question: why, in [this example](https://codesandbox.io/s/getting-started-with-form-atoms-v2-ddhgq2?file=/src/App.tsx) do we see 2 re-renders each time we update a field?

I've tested the code locally and got 4 re-renders, but quickly found out that was due to React's StrictMode.

**To Reproduce**

Just use the example and read the console logs.

**Expected behavior**
1 re-render per field update (maybe?).

**Screenshots**

![image](https://github.com/user-attachments/assets/d9299163-5dde-4da5-9c0e-be22691b316c)

**Additional context**

Many thanks for this library!

**Comment by jaredLunde** [comment]
possibly validation status. could also be react in development mode, not sure

**Comment by wuleninja** [comment]
thanks for this answer!
I have an important question, which probably boils down to my ignorance  in React / Jotai.
If I have an input field as per [your example](https://codesandbox.io/s/getting-started-with-form-atoms-v2-ddhgq2), but of type int, how can I manage to increment its value with a button that I could have right next to it?

**Comment by wuleninja** [comment]
thanks for this answer!
I have an important question, which probably boils down to my ignorance  in React / Jotai.
If I have an input field as per [your example](https://codesandbox.io/s/getting-started-with-form-atoms-v2-ddhgq2), but of type int, how can I manage to increment its value with a button that I could have right next to it?

**Comment by wuleninja** [comment]
I've just figured that I could do `field.actions.setValue(field.state.value - 1);` and spare 1 line 😅😅😅
Great API!!! 👌👌👌

**Comment by wuleninja** [comment]
No need for additional answers regarding the original question.
