### ISSUE TITLE
Question: use with Jotai Effect

### ISSUE THREAD

**Issue by wuleninja** [form-atoms/form-atoms#78]
**Is your feature request related to a problem? Please describe.**
More like an answer to this question: can we make form atoms work with `jotai-effect`?

**Describe the solution you'd like**
Specifically: being able to react to the change of 2 form atoms, to update the value of a third one, with `jotai-effect`. 

**Describe alternatives you've considered**
Using `useEffect` instead but it sucks since it kinda defeats the goodness of form atoms since it causes the re-rendering of the whole form when one of the 2 form atoms changes. 

**Additional context**
I have the particular case where there's only 2 form atoms, the second one needing to be changed if it has some value.

Tried something like this:

```
const updateFieldAtomEffect = atomEffect((get: any, set: any) => {
    if (get(get(fieldAtom1).value) === "someFieldAtom1Value") {
        if (get(get(fieldAtom2).value) === "someFieldAtom2Value") {
            set(get(fieldAtom2).value, "someFieldAtom2Value");
        }
    }
});

Then in form component: `useAtom(updateFieldAtomEffect )`
```

The thing is: the update only occurs once, i.e. the `set(...)` line is only played once. I'll try to provide more context if I have some.

**Comment by wuleninja** [comment]
I've found a workaround, that does not use `jotai-effect`. In the form component that allows to change fieldAtom1 (a select, in my case), I've added the possibility to add an effect.  It seems that to be able to set a form field's value, we have to use hooks (useFieldValue), and, because of React, this has to happen inside a component or custom hook. So I've coded my update logic into a `() => void` function that uses the field values of  fieldAtom1 & fieldAtom2, and pass that to my SelectField component, and this seems to provide enough isolation to not make the whole form re-render when updating these 2 fields.

**Comment by wuleninja** [comment]
Not needed anymore. God I love how this library allows me to do exactly what I wanted! Gracie mille guys!!!
Also, I'm currrently extending the FieldAtom, by encapsuling it in another atom called `FieldConfig`  along with custom hooks (useVisible, useDisabled, useEffects), and constraints (init value, min, max, step - for sliders), so as to have everything at the same place and have very concise forms to write / read. This rocks!

**Comment by Esya** [comment]
@wuleninja Hey! We got the same issue - would you mind sharing your hooks/FieldConfig atom setup, if you're still using them? :)
