### ISSUE TITLE
Submission errors

### ISSUE THREAD

**Issue by shredor** [form-atoms/form-atoms#82]
Hi! Thank you for your lib, it looks great. But I didn't find a recommended way how to handle submission errors.

**Is your feature request related to a problem? Please describe.**
User opens signup form
Enters email/password
Frontend validation passes
Submit handler fired
Backend returns an error "email already exists"
We need to somehow show an error near the username field and reset it when user changes email

**Describe the solution you'd like**
Add example how to handle this case

**Describe alternatives you've considered**
Provide ability to return submission errors in submit handler

**Additional context**

**Comment by MiroslavPetrik** [comment]
Hey, personally with backend validation I display the error on top of the form, not in the field itself. 
I believe that form-atoms is for input validation, which is client side, and your backend validation is _value_ validation.

But if you want to set the field errors, there is the `setErrors` action available from the [useFieldActions()](https://github.com/form-atoms/form-atoms?tab=readme-ov-file#usefieldactions) hook.  

one way:
![image](https://github.com/user-attachments/assets/790ed985-5e2a-4a7c-8287-dc772b24cba7)
