### ISSUE TITLE
Question: How to name formAtom

### ISSUE THREAD

**Issue by pgangwani** [form-atoms/form-atoms#84]
**Is your feature request related to a problem? Please describe.**
I am not sure if there is a way to have added name to formAtom so that we can easily access in jotai devtools

**Describe the solution you'd like**
I would like to know if there is any parameters called as name in form atom like fieldAtom  to debug better in the jotai devtool:

 ![Screenshot 2024-11-20 at 12 39 40 AM](https://github.com/user-attachments/assets/a6f67c82-1062-44e7-9dec-015141118a20)
 
In above exmple, how to give debugLabel/name to `atom541`

**Describe alternatives you've considered**
I tried name & debugLabel but nothing worked out.

**Additional context**
NA

**Comment by MiroslavPetrik** [comment]
Usually there is one form on a page, so the atoms labels started with `form/*` belong to that form. 
Custom name would make sense if you have 2+ forms on a page, and want to avoid search which id belongs to which form.

I believe you can rename the atoms with a custom hook:

```ts
import {useAtomValue} from "jotai";

function useDebugLabel(form: FormAtom<unknown>, name: string) {
  const formAtoms = useAtomValue(form);

  if (typeof process !== "undefined" && process.env.NODE_ENV !== "production") {
    form.debugLabel = `form/${name}`;
    Object.entries(formAtoms).map(([atomName, atom]) => {
      if (isAtom(atom)) {
        atom.debugLabel = `${form.debugLabel}/${atomName}`;
      }
    });
  }

  function isAtom(maybeAtom: any): maybeAtom is FieldAtom<any> {
    return (
      maybeAtom !== null &&
      typeof maybeAtom === "object" &&
      (typeof maybeAtom.read === "function" ||
        typeof maybeAtom.write === "function")
    );
  }

}
```

**Comment by pgangwani** [comment]
> Usually there is one form on a page, so the atoms labels started with `form/*` belong to that form. Custom name would make sense if you have 2+ forms on a page, and want to avoid search which id belongs to which form.
> 
> I believe you can rename the atoms with a custom hook:
> 
> ```ts
> import {useAtomValue} from "jotai";
> 
> function useDebugLabel(form: FormAtom<unknown>, name: string) {
>   const formAtoms = useAtomValue(form);
> 
>   if (typeof process !== "undefined" && process.env.NODE_ENV !== "production") {
>     form.debugLabel = `form/${name}`;
>     Object.entries(formAtoms).map(([atomName, atom]) => {
>       if (isAtom(atom)) {
>         atom.debugLabel = `${form.debugLabel}/${atomName}`;
>       }
>     });
>   }
> 
>   function isAtom(maybeAtom: any): maybeAtom is FieldAtom<any> {
>     return (
>       maybeAtom !== null &&
>       typeof maybeAtom === "object" &&
>       (typeof maybeAtom.read === "function" ||
>         typeof maybeAtom.write === "function")
>     );
>   }
> 
> }
> ```

Thank you so much will give it a try
